spring.application.name=learnsphere

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.datasource.hikari.maximum-pool-size=10
jwt.secret=${JWT}
jwt.expiration=${JWT_EXP}